[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
